First backbone
Usagib/DisplayingandInputtingData pull request #1
Opened 2019-08-15 19:16 UTC by Usagib

code review pull request for project: Displaying and inputting data

2019-08-16 07:47 UTC, samgaco requested changes
### Hi @Usagib and @sebastianlujan :hand: 

### Great work :clap: and well-done readme file :+1: ,  only a few points to address before proceeding:

* Correct the errors in the index file given to you by the [validator](https://validator.w3.org).
* In your [project](https://rawcdn.githack.com/Usagib/DisplayingandInputtingData/ff989e0c43f8074aa51984ac6055437ee3627a6f/index.html) the bottom part of the white box doesn't look the same as in the original:

> ![intuit](https://user-images.githubusercontent.com/34820784/63151471-dc9c9a00-c009-11e9-9a6a-60308bbaef2a.png)

* Fix the linters checks that have failed

* **[SUGGESTED]** You could add a live demo of the site in your readme file using https://raw.githack.com/ for example

### Please :pray: submit back for another code review when you are done with these changes :muscle:

2019-08-16 07:47 UTC, samgaco commented on index.html
> +			<!--	<img class="s-logo" src="https://cdn4.iconfinder.com/data/icons/epic-outlines/30/667814-lock_4-512.png" alt="" /> -->
It is better to avoid commented code in your projects.

2019-08-20 17:09 UTC, Usagib commented
Hello Team!
we made the proper changes:
- We passed the validator test
- Corrected lint style errors
- Added some margins and background color to the form footer
- Added a LiveDemo using GitHub Pages!

Heading out the pull request for code review, Happy coding!

2019-08-20 22:39 UTC, Oghenebrume50 approved these changes
Hi team this is approved, good Job :+1:

2019-08-21 15:47 UTC, merged